
if 1:

    token = ""     
    
    # [ REQUIRED ]
    ####################################
    # Auth token from Telegram
    # -->   for how to get one, see
    #       https://core.telegram.org/bots#3-how-do-i-create-a-bot
    ####################################
    # token looks like this: 98687878:OWHIGEerjo3jh27khn....


    id_my_admin = ""
    
    #[ OPTIONAL - id_my_admin is optional ]
    ####################################
    # Id of telegram account from admin (yourself)
    # -->   for how to find your id, see
    #       http://stackoverflow.com/questions/31078710/how-to-obtain-telegram-chat-id-for-a-specific-user
    #       http://stackoverflow.com/questions/32683992/find-out-my-own-user-id-for-sending-a-message-with-telegram-api
    ####################################
    # id looks like this: 78925...
    
    # how often to check FH - Server for changes
    minutes_between_requests = 10

    link_type_id = ""
    # link_type_id looks like this: "type=9797006&id=906"
    # needs to be generated by visiting the website http://www.hof-university.de/ ... 
    
    # Endpoints  = List of channels to notify
    
    id_bot_gruppe = "" #enter id of group, that you want to send the message to

    # for debugging set endpoints to id_my_admin 
    if 0:
        endpoints = [id_my_admin]
    else:
        endpoints = [id_bot_gruppe]
    
    
    